features:
  github: true
  discord: true
  askaquestion: true
  faq: true
  changelog: true
  errata: true

links:
  github: https://github.com/buriedgiantstudios
  discord: https://discord.gg/UjACmFhyKw
  ruleslibrary: https://rules.buriedgiantstudios.com
  askaquestion: mailto:hello@buriedgiantstudios.com
  creator: mailto:kyle@seiyria.com

# https://ionic.io/ionicons
icons:
  topbar:
    advanced: funnel-outline
    syntax: help-circle-outline
    products: file-tray-full-outline

  advanced:
    CardName: person-outline
    CardText: document-text-outline
    FAQ: chatbubbles-outline
    Errata: flask-outline
    Product: game-controller-outline
    Subproducts: hardware-chip-outline
    Tags: pricetags-outline

    Keys: bookmark-outline
    Act: bookmark-outline
    Complexity: bookmark-outline

    Defense: bookmark-outline
    CardCapacity: bookmark-outline

colors:
  syntax:
    ID: '#8360c3'
    Name: '#6370ff'
    CardText: '#06aa3c'
    Errata: '#aa3c06'
    FAQ: '#aa063c'
    Game: '#d0312d'
    Product: '#a16800'
    Tag: '#608b7d'
